# permissions for end users to view dnclabreplicasets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dnclabreplicaset-viewer-role
rules:
- apiGroups:
  - mycore.ds.korea.ac.kr
  resources:
  - dnclabreplicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mycore.ds.korea.ac.kr
  resources:
  - dnclabreplicasets/status
  verbs:
  - get
