
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - mycore.ds.korea.ac.kr
  resources:
  - dnclabreplicasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mycore.ds.korea.ac.kr
  resources:
  - dnclabreplicasets/finalizers
  verbs:
  - update
- apiGroups:
  - mycore.ds.korea.ac.kr
  resources:
  - dnclabreplicasets/status
  verbs:
  - get
  - patch
  - update
